readme: README.md
author: Vinh Nguyen
author_url: https://github.com/ninjaprox
github_url: https://github.com/ninjaprox/NVActivityIndicatorView

theme: fullwidth
disable_search: true
hide_documentation_coverage: true
clean: true

module: NVActivityIndicatorView
module_version: 5.0.0
build_tool_arguments:
- -scheme
- NVActivityIndicatorView-Package
- -project
- NVActivityIndicatorView.xcodeproj
